kind: resource
version: v2
templates:
    - metadata:
          allow_duplicate: false
          table_name: collaboration_environment
          unique_keys: [ "organization_id", "name" ]
      specs:
          - column_name: id
            default_value: 1
            data_type: java.lang.Long
          - column_name: ruleset_id
            value_from:
                field_ref:
                    ref_file: 4.2.0/V_4_2_0_20__regulation_ruleset.yaml
                    field_path: templates.0.specs.0.value
          - column_name: name
            value: ${com.oceanbase.odc.builtin-resource.collaboration.environment.dev.name}
          - column_name: description
            value: ${com.oceanbase.odc.builtin-resource.collaboration.environment.dev.description}
          - column_name: style
            value: "GREEN"
          - column_name: organization_id
            value: ${ORGANIZATION_ID}
            data_type: java.lang.Long
          - column_name: is_builtin
            value: true
            data_type: java.lang.Boolean
          - column_name: creator_id
            value: ${CREATOR_ID}
            data_type: java.lang.Long
          - column_name: last_modifier_id
            value: ${CREATOR_ID}
            data_type: java.lang.Long
    - metadata:
          allow_duplicate: false
          table_name: collaboration_environment
          unique_keys: [ "organization_id", "name" ]
      specs:
          - column_name: id
            default_value: 2
            data_type: java.lang.Long
          - column_name: ruleset_id
            value_from:
                field_ref:
                    ref_file: 4.2.0/V_4_2_0_20__regulation_ruleset.yaml
                    field_path: templates.1.specs.0.value
          - column_name: name
            value: ${com.oceanbase.odc.builtin-resource.collaboration.environment.sit.name}
          - column_name: description
            value: ${com.oceanbase.odc.builtin-resource.collaboration.environment.sit.description}
          - column_name: style
            value: "ORANGE"
          - column_name: organization_id
            value: ${ORGANIZATION_ID}
            data_type: java.lang.Long
          - column_name: is_builtin
            value: true
            data_type: java.lang.Boolean
          - column_name: creator_id
            value: ${CREATOR_ID}
            data_type: java.lang.Long
          - column_name: last_modifier_id
            value: ${CREATOR_ID}
            data_type: java.lang.Long
    - metadata:
          allow_duplicate: false
          table_name: collaboration_environment
          unique_keys: [ "organization_id", "name" ]
      specs:
          - column_name: id
            default_value: 3
            data_type: java.lang.Long
          - column_name: ruleset_id
            value_from:
                field_ref:
                    ref_file: 4.2.0/V_4_2_0_20__regulation_ruleset.yaml
                    field_path: templates.2.specs.0.value
          - column_name: name
            value: ${com.oceanbase.odc.builtin-resource.collaboration.environment.prod.name}
          - column_name: description
            value: ${com.oceanbase.odc.builtin-resource.collaboration.environment.prod.description}
          - column_name: style
            value: "RED"
          - column_name: organization_id
            value: ${ORGANIZATION_ID}
            data_type: java.lang.Long
          - column_name: is_builtin
            value: true
            data_type: java.lang.Boolean
          - column_name: creator_id
            value: ${CREATOR_ID}
            data_type: java.lang.Long
          - column_name: last_modifier_id
            value: ${CREATOR_ID}
            data_type: java.lang.Long
    - metadata:
          allow_duplicate: false
          table_name: collaboration_environment
          unique_keys: [ "organization_id", "name" ]
      specs:
          - column_name: id
            default_value: 4
            data_type: java.lang.Long
          - column_name: ruleset_id
            value_from:
                field_ref:
                    ref_file: 4.2.0/V_4_2_0_20__regulation_ruleset.yaml
                    field_path: templates.3.specs.0.value
          - column_name: name
            value: ${com.oceanbase.odc.builtin-resource.collaboration.environment.default.name}
          - column_name: description
            value: ${com.oceanbase.odc.builtin-resource.collaboration.environment.default.description}
          - column_name: style
            value: "GRAY"
          - column_name: organization_id
            value: ${ORGANIZATION_ID}
            data_type: java.lang.Long
          - column_name: is_builtin
            value: true
            data_type: java.lang.Boolean
          - column_name: creator_id
            value: ${CREATOR_ID}
            data_type: java.lang.Long
          - column_name: last_modifier_id
            value: ${CREATOR_ID}
            data_type: java.lang.Long